In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [5]:
type(a2)

numpy.ndarray

In [6]:
#list of lists
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
b.ndim

2

In [9]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [10]:
b=np.ones(3)
b

array([1., 1., 1.])

In [11]:
b=np.empty(3)
b

array([1., 1., 1.])

In [12]:
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [13]:
# with specific range of elements
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [14]:
# continue
e=np.arange(2,20,2)
e

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
#linear spaced array
h=np.linspace(0,10,num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
# specific datatypes in array
i=np.ones(5, dtype=np.int64)
i

array([1, 1, 1, 1, 1], dtype=int64)

In [18]:
j=np.ones(6, dtype=np.float32)

In [19]:
j

array([1., 1., 1., 1., 1., 1.], dtype=float32)

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# making and reshaping a 3d array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])